spring:
  datasource:
    # 初始化线程池数量  最大数  最小数
    type: com.alibaba.druid.pool.DruidDataSource
    # 驱动包 8.0以上的配置
    # =========== durid 连接池配置===========
    druid:
      #===========JDBC 配置===========
      url: jdbc:mysql://127.0.0.1:3306/crm_project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 5
      max-active: 20
      min-idle: 3
  rabbitmq:
    addresses: 42.194.208.96
    port: 5672
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
server:
  port: 8082